[codespace_remote]
proconnect-codespace ansible_host=cs.psychic-yodel-7v7pwxpj7gx93pj9w.main ansible_user=node ansible_connection=ssh ansible_ssh_common_args='-F "/home/gury/nest/Proyecto Pro-Connect/Pro-Connect/infra/codespaces-ssh/ssh_config"'
