export enum Role {
  USER = 'USER',
  PROFESSIONAL = 'PROFESSIONAL'
}

export enum ServiceMode {
  ONLINE = 'ONLINE',
  IN_PERSON = 'IN_PERSON'
}

export enum ReservationStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED'
}

export enum NotificationType {
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  RESERVATION_UPDATED = 'RESERVATION_UPDATED',
  RESERVATION_CANCELLED = 'RESERVATION_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE'
}